### ISSUE TITLE
Yellow Text/Highlight Missing

### ISSUE THREAD

**Issue by tmose1106** [fdev/sciibo#1]
Hello, I just downloaded your game based off of how splendid the graphics looked. But while running it, I have noticed that most of the highlight is missing.

Below I have included a few screenshots in different terminal emulators running on my Arch Linux install using the latest version of Python (commit 58ed7307ea0b5c5aa052291ebc3030f314f938d8) from GitHub.

## termite (themed)
![2018-06-27_12-02](https://user-images.githubusercontent.com/15310560/41985775-44ce1472-7a02-11e8-9ea1-03b8f88fcc36.png)
## xterm (stock)
![2018-06-27_12-03](https://user-images.githubusercontent.com/15310560/41985777-44db37ce-7a02-11e8-94d9-e45b9f00e33e.png)
## kitty (stock)
![2018-06-27_12-03_1](https://user-images.githubusercontent.com/15310560/41985778-44e78736-7a02-11e8-803c-5e54a570807a.png)
## rxvt-unicode (stock)
![2018-06-27_12-04](https://user-images.githubusercontent.com/15310560/41985779-44f6b396-7a02-11e8-8883-0cddc66c10e9.png)

P.S., Might I ask what terminal emulator you were testing this program with?

**Comment by fdev** [comment]
Apologies for the late reply, GitHub didn't notify me when you opened this issue.

Before releasing the code I tested the game on Ubuntu, Windows and Mac, all of which ran the game just fine.

Just now I tried a bunch of the terminals you mentioned (running on Ubuntu) and here are my results:

### Gnome terminal
![gnome-terminal](https://user-images.githubusercontent.com/1277208/43836265-1821c93a-9b15-11e8-9488-7ba4dcf23c71.png)

### rxvt-unicode
![rxvt-unicode](https://user-images.githubusercontent.com/1277208/43836266-183ede3a-9b15-11e8-91e6-350a593e240f.png)

### xterm
![xterm](https://user-images.githubusercontent.com/1277208/43836267-18581a1c-9b15-11e8-97c0-c92087a98c83.png)

I suspect this is specific to Arch, since I can't reproduce it on Ubuntu. Have you come across this behavior with other applications that use ncurses?
